# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Thwump' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Thwump

end

target 'Thwump MessagesExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Thwump MessagesExtension
  pod 'Alamofire', '~> 5.1'
end
